const shoepActionType = {
    "FETCH_COLLECTION_START": "FETCH_COLLECTION_START",
    "FETCH_COLLECTION_SUCCESS": "FETCH_COLLECTION_SUCCESS",
    "FETCH_COLLECTION_FAILURE": "FETCH_COLLECTION_FAILURE",
    "CLEAR_CART": "CLEAR_CART"
}

export default shoepActionType;